"""Generate tugamorph/_ido_infinitives.py from the tugalex pronunciation lexicon.

The ``-ido/-ida/-idos/-idas`` participle ending is shared by the 2nd (``-er``)
and the 3rd (``-ir``) conjugation, so the ending alone cannot say which
infinitive a participle comes from. This script collects every ``-er`` and
``-ir`` infinitive that the lexicon attests, so the analyzer can emit a lemma
only when exactly one of the two candidates is a real word.

Source: TigreGotico/tugalex, ``tugalex/data/regional_dict.csv.gz``
(columns ``word,phones,syllables,region_code``).

Usage: python3 scripts/gen_ido_infinitives.py <path to regional_dict.csv.gz>
"""
import gzip
import sys
from pathlib import Path

def main(src: str) -> None:
    words = set()
    with gzip.open(src, "rt", encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("#") or line.startswith("word,"):
                continue
            words.add(line.split(",", 1)[0].strip())
    inf = sorted(w for w in words if len(w) > 3 and (w.endswith("er") or w.endswith("ir")))
    out = Path(__file__).resolve().parent.parent / "tugamorph" / "_ido_infinitives.py"
    body = [
        '"""Attested 2nd and 3rd conjugation infinitives (generated, do not edit).',
        "",
        "Generated by ``scripts/gen_ido_infinitives.py`` from the tugalex",
        "pronunciation lexicon ``tugalex/data/regional_dict.csv.gz``.",
        "",
        f"Lexicon words read: {len(words)}. Infinitives kept: {len(inf)}.",
        '"""',
        "",
        "ATTESTED_INFINITIVES = frozenset((",
    ]
    for w in inf:
        body.append(f"    {w!r},")
    body.append("))")
    body.append("")
    out.write_text("\n".join(body), encoding="utf-8")
    print(f"{len(words)} words read, {len(inf)} infinitives written to {out}")

if __name__ == "__main__":
    main(sys.argv[1])
